#index:
#    path: /
#    controller: App\Controller\DefaultController::index

history:
    path: /history
    controller: history_controller:history
    methods: ['GET', 'OPTIONS']

list:
    path: /list
    controller: polen_controller:listPolens
    methods: ['GET', 'OPTIONS']

insert:
    path: /insert
    controller: polen_controller:insertData
    methods: ['POST', 'OPTIONS']

updateLevel:
    path: /update
    controller: polen_controller:updateLevel
    methods: ['POST', 'OPTIONS']

date_overview:
    path: /date/overview
    controller: history_controller:dateOverview
    methods: ['GET', 'OPTIONS']

predict:
    path: /predict
    controller: prediction_controller:predict
    methods: ['GET', 'OPTIONS']

purge_cache:
    path: /cache/purge
    controller: cache_controller:purge
    methods: ['POST', 'OPTIONS']
